source 'https://github.com/CocoaPods/Specs.git'

target 'CKCountdownButton', :exclusive => true do
  pod "CKCountdownButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CKCountdownButton", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'OCMock', '~> 3.1.1'
end
